# Generated by Django 6.1 on 2026-10-04 05:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('biography', models.TextField(blank=True, verbose_name='biografía')),
                ('photo', models.ImageField(blank=True, upload_to='news/authors/', verbose_name='fotografía')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='identificador')),
                ('summary', models.TextField(max_length=600, verbose_name='resumen')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('featured_image', models.ImageField(blank=True, upload_to='news/articles/', verbose_name='imagen destacada')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.author', verbose_name='autor')),
                ('categories', models.ManyToManyField(related_name='articles', to='news.category', verbose_name='categorías')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-published_at', '-pk'],
            },
        ),
    ]
