# Generated by Django 6.1 on 2026-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, max_length=250, verbose_name='crédito de imagen'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='origen de la imagen'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='fuente'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='enlace a la fuente'),
        ),
    ]
