# Generated by Django 6.1 on 2026-09-28 03:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('biography', models.TextField(blank=True, verbose_name='biografia')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('synopsis', models.TextField(blank=True, verbose_name='sinopsis')),
                ('release_year', models.PositiveIntegerField(verbose_name='anio de estreno')),
                ('poster', models.ImageField(blank=True, upload_to='movies/posters/', verbose_name='afiche')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='generos')),
                ('cast', models.ManyToManyField(blank=True, related_name='acted_movies', to='movies.person', verbose_name='reparto')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.person', verbose_name='director')),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='puntuacion')),
                ('comment', models.TextField(blank=True, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie', verbose_name='pelicula')),
            ],
            options={
                'verbose_name': 'valoracion',
                'verbose_name_plural': 'valoraciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
